package com.example.flink;

import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.table.api.EnvironmentSettings;
import org.apache.flink.table.api.TableEnvironment;
import org.apache.flink.configuration.Configuration;

public class KafkaToHdfsJobTableApi {
    public static void main(String[] args) throws Exception {

        // Set up Flink environment with checkpointing and fault tolerance
        Configuration config = new Configuration();
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment(config);
        env.enableCheckpointing(60000); // every 60 seconds
        env.getCheckpointConfig().setCheckpointTimeout(60000);

        // Set up Table API environment
        EnvironmentSettings settings = EnvironmentSettings.newInstance()
                .inStreamingMode()
                .build();

        TableEnvironment tableEnv = TableEnvironment.create(settings);

        // Define Kafka source table
        tableEnv.executeSql(
            """
            CREATE TABLE kafka_source (
                type STRING,
                operation STRING,
                source_table STRING,
                payload_sys_id STRING,
                `timestamp` BIGINT,
                data ROW<
                    aliases STRING,
                    asset STRING,
                    asset_tag STRING,
                    assigned_to STRING,
                    attestation_status STRING,
                    business_criticality STRING,
                    key_1 STRING,
                    key_2 STRING,
                    key_3 STRING,
                    key_4 STRING,
                    key_5 STRING,
                    key_6 STRING,
                    key_7 STRING,
                    key_8 STRING,
                    key_9 STRING,
                    key_10 STRING,
                    key_11 STRING,
                    key_12 STRING,
                    key_13 STRING,
                    key_14 STRING,
                    key_15 STRING,
                    key_16 STRING,
                    key_17 STRING,
                    key_18 STRING,
                    key_19 STRING,
                    key_20 STRING,
                    key_21 STRING,
                    key_22 STRING,
                    key_23 STRING,
                    key_24 STRING,
                    key_25 STRING,
                    key_26 STRING,
                    key_27 STRING,
                    key_28 STRING,
                    key_29 STRING,
                    key_30 STRING,
                    key_31 STRING,
                    key_32 STRING,
                    key_33 STRING,
                    key_34 STRING,
                    key_35 STRING,
                    key_36 STRING,
                    key_37 STRING,
                    key_38 STRING,
                    key_39 STRING,
                    key_40 STRING,
                    key_41 STRING,
                    key_42 STRING,
                    key_43 STRING,
                    key_44 STRING,
                    key_45 STRING,
                    key_46 STRING,
                    key_47 STRING,
                    key_48 STRING,
                    key_49 STRING,
                    key_50 STRING,
                    key_51 STRING,
                    key_52 STRING,
                    key_53 STRING,
                    key_54 STRING,
                    key_55 STRING,
                    key_56 STRING,
                    key_57 STRING,
                    key_58 STRING,
                    key_59 STRING,
                    key_60 STRING,
                    key_61 STRING,
                    key_62 STRING,
                    key_63 STRING,
                    key_64 STRING,
                    key_65 STRING,
                    key_66 STRING,
                    key_67 STRING,
                    key_68 STRING,
                    key_69 STRING,
                    key_70 STRING,
                    key_71 STRING,
                    key_72 STRING,
                    key_73 STRING,
                    key_74 STRING,
                    key_75 STRING,
                    key_76 STRING,
                    key_77 STRING,
                    key_78 STRING,
                    key_79 STRING,
                    key_80 STRING,
                    key_81 STRING,
                    key_82 STRING,
                    key_83 STRING,
                    key_84 STRING,
                    key_85 STRING,
                    key_86 STRING,
                    key_87 STRING,
                    key_88 STRING,
                    key_89 STRING,
                    key_90 STRING,
                    key_91 STRING,
                    key_92 STRING,
                    key_93 STRING,
                    key_94 STRING,
                    key_95 STRING,
                    key_96 STRING,
                    key_97 STRING,
                    key_98 STRING,
                    key_99 STRING,
                    key_100 STRING,
                    key_101 STRING,
                    key_102 STRING,
                    key_103 STRING,
                    key_104 STRING,
                    key_105 STRING,
                    key_106 STRING,
                    key_107 STRING,
                    key_108 STRING,
                    key_109 STRING,
                    key_110 STRING,
                    key_111 STRING,
                    key_112 STRING,
                    key_113 STRING,
                    key_114 STRING,
                    key_115 STRING,
                    key_116 STRING,
                    key_117 STRING,
                    key_118 STRING,
                    key_119 STRING,
                    key_120 STRING,
                    key_121 STRING,
                    key_122 STRING,
                    key_123 STRING,
                    key_124 STRING,
                    key_125 STRING
                >
            ) WITH (
                'connector' = 'kafka',
                'topic' = 'your_topic',
                'properties.bootstrap.servers' = 'your.kafka.broker:9092',
                'properties.group.id' = 'flink-kafka-group',
                'scan.startup.mode' = 'earliest-offset',
                'format' = 'json',
                'json.fail-on-missing-field' = 'false',
                'json.ignore-parse-errors' = 'true'
            )
            """);

        // Define HDFS sink table
        tableEnv.executeSql(
            """
            CREATE TABLE hdfs_sink (
                type STRING,
                operation STRING,
                source_table STRING,
                payload_sys_id STRING,
                `timestamp` BIGINT,
                aliases STRING,
                asset STRING,
                asset_tag STRING,
                assigned_to STRING,
                attestation_status STRING,
                business_criticality STRING,
                key_1 STRING,
                key_2 STRING,
                key_3 STRING,
                key_4 STRING,
                key_5 STRING,
                key_6 STRING,
                key_7 STRING,
                key_8 STRING,
                key_9 STRING,
                key_10 STRING,
                key_11 STRING,
                key_12 STRING,
                key_13 STRING,
                key_14 STRING,
                key_15 STRING,
                key_16 STRING,
                key_17 STRING,
                key_18 STRING,
                key_19 STRING,
                key_20 STRING,
                key_21 STRING,
                key_22 STRING,
                key_23 STRING,
                key_24 STRING,
                key_25 STRING,
                key_26 STRING,
                key_27 STRING,
                key_28 STRING,
                key_29 STRING,
                key_30 STRING,
                key_31 STRING,
                key_32 STRING,
                key_33 STRING,
                key_34 STRING,
                key_35 STRING,
                key_36 STRING,
                key_37 STRING,
                key_38 STRING,
                key_39 STRING,
                key_40 STRING,
                key_41 STRING,
                key_42 STRING,
                key_43 STRING,
                key_44 STRING,
                key_45 STRING,
                key_46 STRING,
                key_47 STRING,
                key_48 STRING,
                key_49 STRING,
                key_50 STRING,
                key_51 STRING,
                key_52 STRING,
                key_53 STRING,
                key_54 STRING,
                key_55 STRING,
                key_56 STRING,
                key_57 STRING,
                key_58 STRING,
                key_59 STRING,
                key_60 STRING,
                key_61 STRING,
                key_62 STRING,
                key_63 STRING,
                key_64 STRING,
                key_65 STRING,
                key_66 STRING,
                key_67 STRING,
                key_68 STRING,
                key_69 STRING,
                key_70 STRING,
                key_71 STRING,
                key_72 STRING,
                key_73 STRING,
                key_74 STRING,
                key_75 STRING,
                key_76 STRING,
                key_77 STRING,
                key_78 STRING,
                key_79 STRING,
                key_80 STRING,
                key_81 STRING,
                key_82 STRING,
                key_83 STRING,
                key_84 STRING,
                key_85 STRING,
                key_86 STRING,
                key_87 STRING,
                key_88 STRING,
                key_89 STRING,
                key_90 STRING,
                key_91 STRING,
                key_92 STRING,
                key_93 STRING,
                key_94 STRING,
                key_95 STRING,
                key_96 STRING,
                key_97 STRING,
                key_98 STRING,
                key_99 STRING,
                key_100 STRING,
                key_101 STRING,
                key_102 STRING,
                key_103 STRING,
                key_104 STRING,
                key_105 STRING,
                key_106 STRING,
                key_107 STRING,
                key_108 STRING,
                key_109 STRING,
                key_110 STRING,
                key_111 STRING,
                key_112 STRING,
                key_113 STRING,
                key_114 STRING,
                key_115 STRING,
                key_116 STRING,
                key_117 STRING,
                key_118 STRING,
                key_119 STRING,
                key_120 STRING,
                key_121 STRING,
                key_122 STRING,
                key_123 STRING,
                key_124 STRING,
                key_125 STRING
            ) WITH (
                'connector' = 'filesystem',
                'path' = 'hdfs://namenode:8020/flink/output/',
                'format' = 'json',
                'sink.rolling-policy.rollover-interval' = '15 min'
            )
            """);

        // Insert into HDFS sink
        tableEnv.executeSql(
            """
            INSERT INTO hdfs_sink
            SELECT
                type,
                operation,
                source_table,
                payload_sys_id,
                `timestamp`,
                data.aliases,
                data.asset,
                data.asset_tag,
                data.assigned_to,
                data.attestation_status,
                data.business_criticality,
                data.key_1,
                data.key_2,
                data.key_3,
                data.key_4,
                data.key_5,
                data.key_6,
                data.key_7,
                data.key_8,
                data.key_9,
                data.key_10,
                data.key_11,
                data.key_12,
                data.key_13,
                data.key_14,
                data.key_15,
                data.key_16,
                data.key_17,
                data.key_18,
                data.key_19,
                data.key_20,
                data.key_21,
                data.key_22,
                data.key_23,
                data.key_24,
                data.key_25,
                data.key_26,
                data.key_27,
                data.key_28,
                data.key_29,
                data.key_30,
                data.key_31,
                data.key_32,
                data.key_33,
                data.key_34,
                data.key_35,
                data.key_36,
                data.key_37,
                data.key_38,
                data.key_39,
                data.key_40,
                data.key_41,
                data.key_42,
                data.key_43,
                data.key_44,
                data.key_45,
                data.key_46,
                data.key_47,
                data.key_48,
                data.key_49,
                data.key_50,
                data.key_51,
                data.key_52,
                data.key_53,
                data.key_54,
                data.key_55,
                data.key_56,
                data.key_57,
                data.key_58,
                data.key_59,
                data.key_60,
                data.key_61,
                data.key_62,
                data.key_63,
                data.key_64,
                data.key_65,
                data.key_66,
                data.key_67,
                data.key_68,
                data.key_69,
                data.key_70,
                data.key_71,
                data.key_72,
                data.key_73,
                data.key_74,
                data.key_75,
                data.key_76,
                data.key_77,
                data.key_78,
                data.key_79,
                data.key_80,
                data.key_81,
                data.key_82,
                data.key_83,
                data.key_84,
                data.key_85,
                data.key_86,
                data.key_87,
                data.key_88,
                data.key_89,
                data.key_90,
                data.key_91,
                data.key_92,
                data.key_93,
                data.key_94,
                data.key_95,
                data.key_96,
                data.key_97,
                data.key_98,
                data.key_99,
                data.key_100,
                data.key_101,
                data.key_102,
                data.key_103,
                data.key_104,
                data.key_105,
                data.key_106,
                data.key_107,
                data.key_108,
                data.key_109,
                data.key_110,
                data.key_111,
                data.key_112,
                data.key_113,
                data.key_114,
                data.key_115,
                data.key_116,
                data.key_117,
                data.key_118,
                data.key_119,
                data.key_120,
                data.key_121,
                data.key_122,
                data.key_123,
                data.key_124,
                data.key_125
            FROM kafka_source
            """);
    }
}
